//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinUI.Tiyi.PMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonBaseInfo", Namespace="http://10.137.70.2/PMS.WebUI")]
    [System.SerializableAttribute()]
    public partial class PersonBaseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        private System.DateTime 出生日期Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 身份证号Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 工种Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 岗位类别Field;
        
        private System.DateTime 参加工作时间Field;
        
        private System.DateTime 进入本系统工作时间Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string JobNumber {
            get {
                return this.JobNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNumberField, value) != true)) {
                    this.JobNumberField = value;
                    this.RaisePropertyChanged("JobNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RealName {
            get {
                return this.RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RealNameField, value) != true)) {
                    this.RealNameField = value;
                    this.RaisePropertyChanged("RealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime 出生日期 {
            get {
                return this.出生日期Field;
            }
            set {
                if ((this.出生日期Field.Equals(value) != true)) {
                    this.出生日期Field = value;
                    this.RaisePropertyChanged("出生日期");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string 身份证号 {
            get {
                return this.身份证号Field;
            }
            set {
                if ((object.ReferenceEquals(this.身份证号Field, value) != true)) {
                    this.身份证号Field = value;
                    this.RaisePropertyChanged("身份证号");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string 工种 {
            get {
                return this.工种Field;
            }
            set {
                if ((object.ReferenceEquals(this.工种Field, value) != true)) {
                    this.工种Field = value;
                    this.RaisePropertyChanged("工种");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string 岗位类别 {
            get {
                return this.岗位类别Field;
            }
            set {
                if ((object.ReferenceEquals(this.岗位类别Field, value) != true)) {
                    this.岗位类别Field = value;
                    this.RaisePropertyChanged("岗位类别");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime 参加工作时间 {
            get {
                return this.参加工作时间Field;
            }
            set {
                if ((this.参加工作时间Field.Equals(value) != true)) {
                    this.参加工作时间Field = value;
                    this.RaisePropertyChanged("参加工作时间");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime 进入本系统工作时间 {
            get {
                return this.进入本系统工作时间Field;
            }
            set {
                if ((this.进入本系统工作时间Field.Equals(value) != true)) {
                    this.进入本系统工作时间Field = value;
                    this.RaisePropertyChanged("进入本系统工作时间");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personnel", Namespace="http://10.137.70.2/PMS.WebUI")]
    [System.SerializableAttribute()]
    public partial class Personnel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorporationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinUI.Tiyi.PMS.Individual IndividualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinUI.Tiyi.PMS.Telephone TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinUI.Tiyi.PMS.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinUI.Tiyi.PMS.ECommunication ECommunicationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string JobNumber {
            get {
                return this.JobNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNumberField, value) != true)) {
                    this.JobNumberField = value;
                    this.RaisePropertyChanged("JobNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Corporation {
            get {
                return this.CorporationField;
            }
            set {
                if ((object.ReferenceEquals(this.CorporationField, value) != true)) {
                    this.CorporationField = value;
                    this.RaisePropertyChanged("Corporation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WinUI.Tiyi.PMS.Individual Individual {
            get {
                return this.IndividualField;
            }
            set {
                if ((object.ReferenceEquals(this.IndividualField, value) != true)) {
                    this.IndividualField = value;
                    this.RaisePropertyChanged("Individual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WinUI.Tiyi.PMS.Telephone Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public WinUI.Tiyi.PMS.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public WinUI.Tiyi.PMS.ECommunication ECommunication {
            get {
                return this.ECommunicationField;
            }
            set {
                if ((object.ReferenceEquals(this.ECommunicationField, value) != true)) {
                    this.ECommunicationField = value;
                    this.RaisePropertyChanged("ECommunication");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Individual", Namespace="http://10.137.70.2/PMS.WebUI")]
    [System.SerializableAttribute()]
    public partial class Individual : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private bool SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentityCardField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IdentityCard {
            get {
                return this.IdentityCardField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityCardField, value) != true)) {
                    this.IdentityCardField = value;
                    this.RaisePropertyChanged("IdentityCard");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telephone", Namespace="http://10.137.70.2/PMS.WebUI")]
    [System.SerializableAttribute()]
    public partial class Telephone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileShort1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileShort2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeTelephone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeTelephone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeFaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessTelephone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessTelephone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessFaxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MobilePhone1 {
            get {
                return this.MobilePhone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhone1Field, value) != true)) {
                    this.MobilePhone1Field = value;
                    this.RaisePropertyChanged("MobilePhone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MobilePhone2 {
            get {
                return this.MobilePhone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhone2Field, value) != true)) {
                    this.MobilePhone2Field = value;
                    this.RaisePropertyChanged("MobilePhone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MobileShort1 {
            get {
                return this.MobileShort1Field;
            }
            set {
                if ((object.ReferenceEquals(this.MobileShort1Field, value) != true)) {
                    this.MobileShort1Field = value;
                    this.RaisePropertyChanged("MobileShort1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MobileShort2 {
            get {
                return this.MobileShort2Field;
            }
            set {
                if ((object.ReferenceEquals(this.MobileShort2Field, value) != true)) {
                    this.MobileShort2Field = value;
                    this.RaisePropertyChanged("MobileShort2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HomeTelephone1 {
            get {
                return this.HomeTelephone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTelephone1Field, value) != true)) {
                    this.HomeTelephone1Field = value;
                    this.RaisePropertyChanged("HomeTelephone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string HomeTelephone2 {
            get {
                return this.HomeTelephone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTelephone2Field, value) != true)) {
                    this.HomeTelephone2Field = value;
                    this.RaisePropertyChanged("HomeTelephone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string HomeFax {
            get {
                return this.HomeFaxField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeFaxField, value) != true)) {
                    this.HomeFaxField = value;
                    this.RaisePropertyChanged("HomeFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string BusinessTelephone1 {
            get {
                return this.BusinessTelephone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessTelephone1Field, value) != true)) {
                    this.BusinessTelephone1Field = value;
                    this.RaisePropertyChanged("BusinessTelephone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string BusinessTelephone2 {
            get {
                return this.BusinessTelephone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessTelephone2Field, value) != true)) {
                    this.BusinessTelephone2Field = value;
                    this.RaisePropertyChanged("BusinessTelephone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string BusinessFax {
            get {
                return this.BusinessFaxField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessFaxField, value) != true)) {
                    this.BusinessFaxField = value;
                    this.RaisePropertyChanged("BusinessFax");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://10.137.70.2/PMS.WebUI")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NativePlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NativePlaceZipcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorporationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorporationZipcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DwellingPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DwellingPlaceZipcodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NativePlace {
            get {
                return this.NativePlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.NativePlaceField, value) != true)) {
                    this.NativePlaceField = value;
                    this.RaisePropertyChanged("NativePlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NativePlaceZipcode {
            get {
                return this.NativePlaceZipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NativePlaceZipcodeField, value) != true)) {
                    this.NativePlaceZipcodeField = value;
                    this.RaisePropertyChanged("NativePlaceZipcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Corporation {
            get {
                return this.CorporationField;
            }
            set {
                if ((object.ReferenceEquals(this.CorporationField, value) != true)) {
                    this.CorporationField = value;
                    this.RaisePropertyChanged("Corporation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CorporationZipcode {
            get {
                return this.CorporationZipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CorporationZipcodeField, value) != true)) {
                    this.CorporationZipcodeField = value;
                    this.RaisePropertyChanged("CorporationZipcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DwellingPlace {
            get {
                return this.DwellingPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.DwellingPlaceField, value) != true)) {
                    this.DwellingPlaceField = value;
                    this.RaisePropertyChanged("DwellingPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DwellingPlaceZipcode {
            get {
                return this.DwellingPlaceZipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DwellingPlaceZipcodeField, value) != true)) {
                    this.DwellingPlaceZipcodeField = value;
                    this.RaisePropertyChanged("DwellingPlaceZipcode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ECommunication", Namespace="http://10.137.70.2/PMS.WebUI")]
    [System.SerializableAttribute()]
    public partial class ECommunication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email1 {
            get {
                return this.Email1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Email1Field, value) != true)) {
                    this.Email1Field = value;
                    this.RaisePropertyChanged("Email1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email2 {
            get {
                return this.Email2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Email2Field, value) != true)) {
                    this.Email2Field = value;
                    this.RaisePropertyChanged("Email2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email3 {
            get {
                return this.Email3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Email3Field, value) != true)) {
                    this.Email3Field = value;
                    this.RaisePropertyChanged("Email3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string QQ {
            get {
                return this.QQField;
            }
            set {
                if ((object.ReferenceEquals(this.QQField, value) != true)) {
                    this.QQField = value;
                    this.RaisePropertyChanged("QQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MSN {
            get {
                return this.MSNField;
            }
            set {
                if ((object.ReferenceEquals(this.MSNField, value) != true)) {
                    this.MSNField = value;
                    this.RaisePropertyChanged("MSN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonInfo", Namespace="http://10.137.70.2/PMS.WebUI")]
    [System.SerializableAttribute()]
    public partial class PersonInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private bool SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileShortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string JobNumber {
            get {
                return this.JobNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNumberField, value) != true)) {
                    this.JobNumberField = value;
                    this.RaisePropertyChanged("JobNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Mobilephone {
            get {
                return this.MobilephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilephoneField, value) != true)) {
                    this.MobilephoneField = value;
                    this.RaisePropertyChanged("Mobilephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MobileShort {
            get {
                return this.MobileShortField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileShortField, value) != true)) {
                    this.MobileShortField = value;
                    this.RaisePropertyChanged("MobileShort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://10.137.70.2/PMS.WebUI")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI", ConfigurationName="Tiyi.PMS.PersonnelRollSoap")]
    public interface PersonnelRollSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.137.70.2/PMS.WebUI/GetPersonBaseInfo_ByJobNumber", ReplyAction="*")]
        WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberResponse GetPersonBaseInfo_ByJobNumber(WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://10.137.70.2/PMS.WebUI/GetPersonBaseInfo_ByJobNumber", ReplyAction="*")]
        System.IAsyncResult BeginGetPersonBaseInfo_ByJobNumber(WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberRequest request, System.AsyncCallback callback, object asyncState);
        
        WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberResponse EndGetPersonBaseInfo_ByJobNumber(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.137.70.2/PMS.WebUI/GetPersonnelByJobNumber", ReplyAction="*")]
        WinUI.Tiyi.PMS.GetPersonnelByJobNumberResponse GetPersonnelByJobNumber(WinUI.Tiyi.PMS.GetPersonnelByJobNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://10.137.70.2/PMS.WebUI/GetPersonnelByJobNumber", ReplyAction="*")]
        System.IAsyncResult BeginGetPersonnelByJobNumber(WinUI.Tiyi.PMS.GetPersonnelByJobNumberRequest request, System.AsyncCallback callback, object asyncState);
        
        WinUI.Tiyi.PMS.GetPersonnelByJobNumberResponse EndGetPersonnelByJobNumber(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.137.70.2/PMS.WebUI/GetPersonInfoByJobNumber", ReplyAction="*")]
        WinUI.Tiyi.PMS.GetPersonInfoByJobNumberResponse GetPersonInfoByJobNumber(WinUI.Tiyi.PMS.GetPersonInfoByJobNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://10.137.70.2/PMS.WebUI/GetPersonInfoByJobNumber", ReplyAction="*")]
        System.IAsyncResult BeginGetPersonInfoByJobNumber(WinUI.Tiyi.PMS.GetPersonInfoByJobNumberRequest request, System.AsyncCallback callback, object asyncState);
        
        WinUI.Tiyi.PMS.GetPersonInfoByJobNumberResponse EndGetPersonInfoByJobNumber(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.137.70.2/PMS.WebUI/GetPersonInfoByBlurInfo", ReplyAction="*")]
        WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoResponse GetPersonInfoByBlurInfo(WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://10.137.70.2/PMS.WebUI/GetPersonInfoByBlurInfo", ReplyAction="*")]
        System.IAsyncResult BeginGetPersonInfoByBlurInfo(WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoResponse EndGetPersonInfoByBlurInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.137.70.2/PMS.WebUI/GetPersonInfoListByDepartment", ReplyAction="*")]
        WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentResponse GetPersonInfoListByDepartment(WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://10.137.70.2/PMS.WebUI/GetPersonInfoListByDepartment", ReplyAction="*")]
        System.IAsyncResult BeginGetPersonInfoListByDepartment(WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentRequest request, System.AsyncCallback callback, object asyncState);
        
        WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentResponse EndGetPersonInfoListByDepartment(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.137.70.2/PMS.WebUI/ExistJobNumber", ReplyAction="*")]
        WinUI.Tiyi.PMS.ExistJobNumberResponse ExistJobNumber(WinUI.Tiyi.PMS.ExistJobNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://10.137.70.2/PMS.WebUI/ExistJobNumber", ReplyAction="*")]
        System.IAsyncResult BeginExistJobNumber(WinUI.Tiyi.PMS.ExistJobNumberRequest request, System.AsyncCallback callback, object asyncState);
        
        WinUI.Tiyi.PMS.ExistJobNumberResponse EndExistJobNumber(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.137.70.2/PMS.WebUI/GetDepartments", ReplyAction="*")]
        WinUI.Tiyi.PMS.GetDepartmentsResponse GetDepartments(WinUI.Tiyi.PMS.GetDepartmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://10.137.70.2/PMS.WebUI/GetDepartments", ReplyAction="*")]
        System.IAsyncResult BeginGetDepartments(WinUI.Tiyi.PMS.GetDepartmentsRequest request, System.AsyncCallback callback, object asyncState);
        
        WinUI.Tiyi.PMS.GetDepartmentsResponse EndGetDepartments(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonBaseInfo_ByJobNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonBaseInfo_ByJobNumber", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberRequestBody Body;
        
        public GetPersonBaseInfo_ByJobNumberRequest() {
        }
        
        public GetPersonBaseInfo_ByJobNumberRequest(WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class GetPersonBaseInfo_ByJobNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jobNumber;
        
        public GetPersonBaseInfo_ByJobNumberRequestBody() {
        }
        
        public GetPersonBaseInfo_ByJobNumberRequestBody(string jobNumber) {
            this.jobNumber = jobNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonBaseInfo_ByJobNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonBaseInfo_ByJobNumberResponse", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberResponseBody Body;
        
        public GetPersonBaseInfo_ByJobNumberResponse() {
        }
        
        public GetPersonBaseInfo_ByJobNumberResponse(WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class GetPersonBaseInfo_ByJobNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WinUI.Tiyi.PMS.PersonBaseInfo GetPersonBaseInfo_ByJobNumberResult;
        
        public GetPersonBaseInfo_ByJobNumberResponseBody() {
        }
        
        public GetPersonBaseInfo_ByJobNumberResponseBody(WinUI.Tiyi.PMS.PersonBaseInfo GetPersonBaseInfo_ByJobNumberResult) {
            this.GetPersonBaseInfo_ByJobNumberResult = GetPersonBaseInfo_ByJobNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonnelByJobNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonnelByJobNumber", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetPersonnelByJobNumberRequestBody Body;
        
        public GetPersonnelByJobNumberRequest() {
        }
        
        public GetPersonnelByJobNumberRequest(WinUI.Tiyi.PMS.GetPersonnelByJobNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class GetPersonnelByJobNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jobNumber;
        
        public GetPersonnelByJobNumberRequestBody() {
        }
        
        public GetPersonnelByJobNumberRequestBody(string jobNumber) {
            this.jobNumber = jobNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonnelByJobNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonnelByJobNumberResponse", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetPersonnelByJobNumberResponseBody Body;
        
        public GetPersonnelByJobNumberResponse() {
        }
        
        public GetPersonnelByJobNumberResponse(WinUI.Tiyi.PMS.GetPersonnelByJobNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class GetPersonnelByJobNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WinUI.Tiyi.PMS.Personnel GetPersonnelByJobNumberResult;
        
        public GetPersonnelByJobNumberResponseBody() {
        }
        
        public GetPersonnelByJobNumberResponseBody(WinUI.Tiyi.PMS.Personnel GetPersonnelByJobNumberResult) {
            this.GetPersonnelByJobNumberResult = GetPersonnelByJobNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonInfoByJobNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonInfoByJobNumber", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetPersonInfoByJobNumberRequestBody Body;
        
        public GetPersonInfoByJobNumberRequest() {
        }
        
        public GetPersonInfoByJobNumberRequest(WinUI.Tiyi.PMS.GetPersonInfoByJobNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class GetPersonInfoByJobNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jobNumber;
        
        public GetPersonInfoByJobNumberRequestBody() {
        }
        
        public GetPersonInfoByJobNumberRequestBody(string jobNumber) {
            this.jobNumber = jobNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonInfoByJobNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonInfoByJobNumberResponse", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetPersonInfoByJobNumberResponseBody Body;
        
        public GetPersonInfoByJobNumberResponse() {
        }
        
        public GetPersonInfoByJobNumberResponse(WinUI.Tiyi.PMS.GetPersonInfoByJobNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class GetPersonInfoByJobNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WinUI.Tiyi.PMS.PersonInfo GetPersonInfoByJobNumberResult;
        
        public GetPersonInfoByJobNumberResponseBody() {
        }
        
        public GetPersonInfoByJobNumberResponseBody(WinUI.Tiyi.PMS.PersonInfo GetPersonInfoByJobNumberResult) {
            this.GetPersonInfoByJobNumberResult = GetPersonInfoByJobNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonInfoByBlurInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonInfoByBlurInfo", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoRequestBody Body;
        
        public GetPersonInfoByBlurInfoRequest() {
        }
        
        public GetPersonInfoByBlurInfoRequest(WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class GetPersonInfoByBlurInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyWord;
        
        public GetPersonInfoByBlurInfoRequestBody() {
        }
        
        public GetPersonInfoByBlurInfoRequestBody(string keyWord) {
            this.keyWord = keyWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonInfoByBlurInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonInfoByBlurInfoResponse", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoResponseBody Body;
        
        public GetPersonInfoByBlurInfoResponse() {
        }
        
        public GetPersonInfoByBlurInfoResponse(WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class GetPersonInfoByBlurInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WinUI.Tiyi.PMS.PersonInfo[] GetPersonInfoByBlurInfoResult;
        
        public GetPersonInfoByBlurInfoResponseBody() {
        }
        
        public GetPersonInfoByBlurInfoResponseBody(WinUI.Tiyi.PMS.PersonInfo[] GetPersonInfoByBlurInfoResult) {
            this.GetPersonInfoByBlurInfoResult = GetPersonInfoByBlurInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonInfoListByDepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonInfoListByDepartment", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentRequestBody Body;
        
        public GetPersonInfoListByDepartmentRequest() {
        }
        
        public GetPersonInfoListByDepartmentRequest(WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class GetPersonInfoListByDepartmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string departmentName;
        
        public GetPersonInfoListByDepartmentRequestBody() {
        }
        
        public GetPersonInfoListByDepartmentRequestBody(string departmentName) {
            this.departmentName = departmentName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonInfoListByDepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonInfoListByDepartmentResponse", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentResponseBody Body;
        
        public GetPersonInfoListByDepartmentResponse() {
        }
        
        public GetPersonInfoListByDepartmentResponse(WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class GetPersonInfoListByDepartmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WinUI.Tiyi.PMS.PersonInfo[] GetPersonInfoListByDepartmentResult;
        
        public GetPersonInfoListByDepartmentResponseBody() {
        }
        
        public GetPersonInfoListByDepartmentResponseBody(WinUI.Tiyi.PMS.PersonInfo[] GetPersonInfoListByDepartmentResult) {
            this.GetPersonInfoListByDepartmentResult = GetPersonInfoListByDepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistJobNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistJobNumber", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.ExistJobNumberRequestBody Body;
        
        public ExistJobNumberRequest() {
        }
        
        public ExistJobNumberRequest(WinUI.Tiyi.PMS.ExistJobNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class ExistJobNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jobNumber;
        
        public ExistJobNumberRequestBody() {
        }
        
        public ExistJobNumberRequestBody(string jobNumber) {
            this.jobNumber = jobNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistJobNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistJobNumberResponse", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.ExistJobNumberResponseBody Body;
        
        public ExistJobNumberResponse() {
        }
        
        public ExistJobNumberResponse(WinUI.Tiyi.PMS.ExistJobNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class ExistJobNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ExistJobNumberResult;
        
        public ExistJobNumberResponseBody() {
        }
        
        public ExistJobNumberResponseBody(bool ExistJobNumberResult) {
            this.ExistJobNumberResult = ExistJobNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartments", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetDepartmentsRequestBody Body;
        
        public GetDepartmentsRequest() {
        }
        
        public GetDepartmentsRequest(WinUI.Tiyi.PMS.GetDepartmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDepartmentsRequestBody {
        
        public GetDepartmentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartmentsResponse", Namespace="http://10.137.70.2/PMS.WebUI", Order=0)]
        public WinUI.Tiyi.PMS.GetDepartmentsResponseBody Body;
        
        public GetDepartmentsResponse() {
        }
        
        public GetDepartmentsResponse(WinUI.Tiyi.PMS.GetDepartmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.137.70.2/PMS.WebUI")]
    public partial class GetDepartmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WinUI.Tiyi.PMS.Department[] GetDepartmentsResult;
        
        public GetDepartmentsResponseBody() {
        }
        
        public GetDepartmentsResponseBody(WinUI.Tiyi.PMS.Department[] GetDepartmentsResult) {
            this.GetDepartmentsResult = GetDepartmentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonnelRollSoapChannel : WinUI.Tiyi.PMS.PersonnelRollSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPersonBaseInfo_ByJobNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPersonBaseInfo_ByJobNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPersonnelByJobNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPersonnelByJobNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WinUI.Tiyi.PMS.GetPersonnelByJobNumberResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinUI.Tiyi.PMS.GetPersonnelByJobNumberResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPersonInfoByJobNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPersonInfoByJobNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WinUI.Tiyi.PMS.GetPersonInfoByJobNumberResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinUI.Tiyi.PMS.GetPersonInfoByJobNumberResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPersonInfoByBlurInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPersonInfoByBlurInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPersonInfoListByDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPersonInfoListByDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExistJobNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExistJobNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WinUI.Tiyi.PMS.ExistJobNumberResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinUI.Tiyi.PMS.ExistJobNumberResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDepartmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDepartmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WinUI.Tiyi.PMS.GetDepartmentsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WinUI.Tiyi.PMS.GetDepartmentsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonnelRollSoapClient : System.ServiceModel.ClientBase<WinUI.Tiyi.PMS.PersonnelRollSoap>, WinUI.Tiyi.PMS.PersonnelRollSoap {
        
        private BeginOperationDelegate onBeginGetPersonBaseInfo_ByJobNumberDelegate;
        
        private EndOperationDelegate onEndGetPersonBaseInfo_ByJobNumberDelegate;
        
        private System.Threading.SendOrPostCallback onGetPersonBaseInfo_ByJobNumberCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPersonnelByJobNumberDelegate;
        
        private EndOperationDelegate onEndGetPersonnelByJobNumberDelegate;
        
        private System.Threading.SendOrPostCallback onGetPersonnelByJobNumberCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPersonInfoByJobNumberDelegate;
        
        private EndOperationDelegate onEndGetPersonInfoByJobNumberDelegate;
        
        private System.Threading.SendOrPostCallback onGetPersonInfoByJobNumberCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPersonInfoByBlurInfoDelegate;
        
        private EndOperationDelegate onEndGetPersonInfoByBlurInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetPersonInfoByBlurInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPersonInfoListByDepartmentDelegate;
        
        private EndOperationDelegate onEndGetPersonInfoListByDepartmentDelegate;
        
        private System.Threading.SendOrPostCallback onGetPersonInfoListByDepartmentCompletedDelegate;
        
        private BeginOperationDelegate onBeginExistJobNumberDelegate;
        
        private EndOperationDelegate onEndExistJobNumberDelegate;
        
        private System.Threading.SendOrPostCallback onExistJobNumberCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDepartmentsDelegate;
        
        private EndOperationDelegate onEndGetDepartmentsDelegate;
        
        private System.Threading.SendOrPostCallback onGetDepartmentsCompletedDelegate;
        
        public PersonnelRollSoapClient() {
        }
        
        public PersonnelRollSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonnelRollSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonnelRollSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonnelRollSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetPersonBaseInfo_ByJobNumberCompletedEventArgs> GetPersonBaseInfo_ByJobNumberCompleted;
        
        public event System.EventHandler<GetPersonnelByJobNumberCompletedEventArgs> GetPersonnelByJobNumberCompleted;
        
        public event System.EventHandler<GetPersonInfoByJobNumberCompletedEventArgs> GetPersonInfoByJobNumberCompleted;
        
        public event System.EventHandler<GetPersonInfoByBlurInfoCompletedEventArgs> GetPersonInfoByBlurInfoCompleted;
        
        public event System.EventHandler<GetPersonInfoListByDepartmentCompletedEventArgs> GetPersonInfoListByDepartmentCompleted;
        
        public event System.EventHandler<ExistJobNumberCompletedEventArgs> ExistJobNumberCompleted;
        
        public event System.EventHandler<GetDepartmentsCompletedEventArgs> GetDepartmentsCompleted;
        
        public WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberResponse GetPersonBaseInfo_ByJobNumber(WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberRequest request) {
            return base.Channel.GetPersonBaseInfo_ByJobNumber(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPersonBaseInfo_ByJobNumber(WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPersonBaseInfo_ByJobNumber(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberResponse EndGetPersonBaseInfo_ByJobNumber(System.IAsyncResult result) {
            return base.Channel.EndGetPersonBaseInfo_ByJobNumber(result);
        }
        
        private System.IAsyncResult OnBeginGetPersonBaseInfo_ByJobNumber(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberRequest request = ((WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberRequest)(inValues[0]));
            return this.BeginGetPersonBaseInfo_ByJobNumber(request, callback, asyncState);
        }
        
        private object[] OnEndGetPersonBaseInfo_ByJobNumber(System.IAsyncResult result) {
            WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberResponse retVal = this.EndGetPersonBaseInfo_ByJobNumber(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPersonBaseInfo_ByJobNumberCompleted(object state) {
            if ((this.GetPersonBaseInfo_ByJobNumberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPersonBaseInfo_ByJobNumberCompleted(this, new GetPersonBaseInfo_ByJobNumberCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPersonBaseInfo_ByJobNumberAsync(WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberRequest request) {
            this.GetPersonBaseInfo_ByJobNumberAsync(request, null);
        }
        
        public void GetPersonBaseInfo_ByJobNumberAsync(WinUI.Tiyi.PMS.GetPersonBaseInfo_ByJobNumberRequest request, object userState) {
            if ((this.onBeginGetPersonBaseInfo_ByJobNumberDelegate == null)) {
                this.onBeginGetPersonBaseInfo_ByJobNumberDelegate = new BeginOperationDelegate(this.OnBeginGetPersonBaseInfo_ByJobNumber);
            }
            if ((this.onEndGetPersonBaseInfo_ByJobNumberDelegate == null)) {
                this.onEndGetPersonBaseInfo_ByJobNumberDelegate = new EndOperationDelegate(this.OnEndGetPersonBaseInfo_ByJobNumber);
            }
            if ((this.onGetPersonBaseInfo_ByJobNumberCompletedDelegate == null)) {
                this.onGetPersonBaseInfo_ByJobNumberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPersonBaseInfo_ByJobNumberCompleted);
            }
            base.InvokeAsync(this.onBeginGetPersonBaseInfo_ByJobNumberDelegate, new object[] {
                        request}, this.onEndGetPersonBaseInfo_ByJobNumberDelegate, this.onGetPersonBaseInfo_ByJobNumberCompletedDelegate, userState);
        }
        
        public WinUI.Tiyi.PMS.GetPersonnelByJobNumberResponse GetPersonnelByJobNumber(WinUI.Tiyi.PMS.GetPersonnelByJobNumberRequest request) {
            return base.Channel.GetPersonnelByJobNumber(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPersonnelByJobNumber(WinUI.Tiyi.PMS.GetPersonnelByJobNumberRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPersonnelByJobNumber(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WinUI.Tiyi.PMS.GetPersonnelByJobNumberResponse EndGetPersonnelByJobNumber(System.IAsyncResult result) {
            return base.Channel.EndGetPersonnelByJobNumber(result);
        }
        
        private System.IAsyncResult OnBeginGetPersonnelByJobNumber(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WinUI.Tiyi.PMS.GetPersonnelByJobNumberRequest request = ((WinUI.Tiyi.PMS.GetPersonnelByJobNumberRequest)(inValues[0]));
            return this.BeginGetPersonnelByJobNumber(request, callback, asyncState);
        }
        
        private object[] OnEndGetPersonnelByJobNumber(System.IAsyncResult result) {
            WinUI.Tiyi.PMS.GetPersonnelByJobNumberResponse retVal = this.EndGetPersonnelByJobNumber(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPersonnelByJobNumberCompleted(object state) {
            if ((this.GetPersonnelByJobNumberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPersonnelByJobNumberCompleted(this, new GetPersonnelByJobNumberCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPersonnelByJobNumberAsync(WinUI.Tiyi.PMS.GetPersonnelByJobNumberRequest request) {
            this.GetPersonnelByJobNumberAsync(request, null);
        }
        
        public void GetPersonnelByJobNumberAsync(WinUI.Tiyi.PMS.GetPersonnelByJobNumberRequest request, object userState) {
            if ((this.onBeginGetPersonnelByJobNumberDelegate == null)) {
                this.onBeginGetPersonnelByJobNumberDelegate = new BeginOperationDelegate(this.OnBeginGetPersonnelByJobNumber);
            }
            if ((this.onEndGetPersonnelByJobNumberDelegate == null)) {
                this.onEndGetPersonnelByJobNumberDelegate = new EndOperationDelegate(this.OnEndGetPersonnelByJobNumber);
            }
            if ((this.onGetPersonnelByJobNumberCompletedDelegate == null)) {
                this.onGetPersonnelByJobNumberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPersonnelByJobNumberCompleted);
            }
            base.InvokeAsync(this.onBeginGetPersonnelByJobNumberDelegate, new object[] {
                        request}, this.onEndGetPersonnelByJobNumberDelegate, this.onGetPersonnelByJobNumberCompletedDelegate, userState);
        }
        
        public WinUI.Tiyi.PMS.GetPersonInfoByJobNumberResponse GetPersonInfoByJobNumber(WinUI.Tiyi.PMS.GetPersonInfoByJobNumberRequest request) {
            return base.Channel.GetPersonInfoByJobNumber(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPersonInfoByJobNumber(WinUI.Tiyi.PMS.GetPersonInfoByJobNumberRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPersonInfoByJobNumber(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WinUI.Tiyi.PMS.GetPersonInfoByJobNumberResponse EndGetPersonInfoByJobNumber(System.IAsyncResult result) {
            return base.Channel.EndGetPersonInfoByJobNumber(result);
        }
        
        private System.IAsyncResult OnBeginGetPersonInfoByJobNumber(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WinUI.Tiyi.PMS.GetPersonInfoByJobNumberRequest request = ((WinUI.Tiyi.PMS.GetPersonInfoByJobNumberRequest)(inValues[0]));
            return this.BeginGetPersonInfoByJobNumber(request, callback, asyncState);
        }
        
        private object[] OnEndGetPersonInfoByJobNumber(System.IAsyncResult result) {
            WinUI.Tiyi.PMS.GetPersonInfoByJobNumberResponse retVal = this.EndGetPersonInfoByJobNumber(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPersonInfoByJobNumberCompleted(object state) {
            if ((this.GetPersonInfoByJobNumberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPersonInfoByJobNumberCompleted(this, new GetPersonInfoByJobNumberCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPersonInfoByJobNumberAsync(WinUI.Tiyi.PMS.GetPersonInfoByJobNumberRequest request) {
            this.GetPersonInfoByJobNumberAsync(request, null);
        }
        
        public void GetPersonInfoByJobNumberAsync(WinUI.Tiyi.PMS.GetPersonInfoByJobNumberRequest request, object userState) {
            if ((this.onBeginGetPersonInfoByJobNumberDelegate == null)) {
                this.onBeginGetPersonInfoByJobNumberDelegate = new BeginOperationDelegate(this.OnBeginGetPersonInfoByJobNumber);
            }
            if ((this.onEndGetPersonInfoByJobNumberDelegate == null)) {
                this.onEndGetPersonInfoByJobNumberDelegate = new EndOperationDelegate(this.OnEndGetPersonInfoByJobNumber);
            }
            if ((this.onGetPersonInfoByJobNumberCompletedDelegate == null)) {
                this.onGetPersonInfoByJobNumberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPersonInfoByJobNumberCompleted);
            }
            base.InvokeAsync(this.onBeginGetPersonInfoByJobNumberDelegate, new object[] {
                        request}, this.onEndGetPersonInfoByJobNumberDelegate, this.onGetPersonInfoByJobNumberCompletedDelegate, userState);
        }
        
        public WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoResponse GetPersonInfoByBlurInfo(WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoRequest request) {
            return base.Channel.GetPersonInfoByBlurInfo(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPersonInfoByBlurInfo(WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPersonInfoByBlurInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoResponse EndGetPersonInfoByBlurInfo(System.IAsyncResult result) {
            return base.Channel.EndGetPersonInfoByBlurInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetPersonInfoByBlurInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoRequest request = ((WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoRequest)(inValues[0]));
            return this.BeginGetPersonInfoByBlurInfo(request, callback, asyncState);
        }
        
        private object[] OnEndGetPersonInfoByBlurInfo(System.IAsyncResult result) {
            WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoResponse retVal = this.EndGetPersonInfoByBlurInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPersonInfoByBlurInfoCompleted(object state) {
            if ((this.GetPersonInfoByBlurInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPersonInfoByBlurInfoCompleted(this, new GetPersonInfoByBlurInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPersonInfoByBlurInfoAsync(WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoRequest request) {
            this.GetPersonInfoByBlurInfoAsync(request, null);
        }
        
        public void GetPersonInfoByBlurInfoAsync(WinUI.Tiyi.PMS.GetPersonInfoByBlurInfoRequest request, object userState) {
            if ((this.onBeginGetPersonInfoByBlurInfoDelegate == null)) {
                this.onBeginGetPersonInfoByBlurInfoDelegate = new BeginOperationDelegate(this.OnBeginGetPersonInfoByBlurInfo);
            }
            if ((this.onEndGetPersonInfoByBlurInfoDelegate == null)) {
                this.onEndGetPersonInfoByBlurInfoDelegate = new EndOperationDelegate(this.OnEndGetPersonInfoByBlurInfo);
            }
            if ((this.onGetPersonInfoByBlurInfoCompletedDelegate == null)) {
                this.onGetPersonInfoByBlurInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPersonInfoByBlurInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetPersonInfoByBlurInfoDelegate, new object[] {
                        request}, this.onEndGetPersonInfoByBlurInfoDelegate, this.onGetPersonInfoByBlurInfoCompletedDelegate, userState);
        }
        
        public WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentResponse GetPersonInfoListByDepartment(WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentRequest request) {
            return base.Channel.GetPersonInfoListByDepartment(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPersonInfoListByDepartment(WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPersonInfoListByDepartment(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentResponse EndGetPersonInfoListByDepartment(System.IAsyncResult result) {
            return base.Channel.EndGetPersonInfoListByDepartment(result);
        }
        
        private System.IAsyncResult OnBeginGetPersonInfoListByDepartment(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentRequest request = ((WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentRequest)(inValues[0]));
            return this.BeginGetPersonInfoListByDepartment(request, callback, asyncState);
        }
        
        private object[] OnEndGetPersonInfoListByDepartment(System.IAsyncResult result) {
            WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentResponse retVal = this.EndGetPersonInfoListByDepartment(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPersonInfoListByDepartmentCompleted(object state) {
            if ((this.GetPersonInfoListByDepartmentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPersonInfoListByDepartmentCompleted(this, new GetPersonInfoListByDepartmentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPersonInfoListByDepartmentAsync(WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentRequest request) {
            this.GetPersonInfoListByDepartmentAsync(request, null);
        }
        
        public void GetPersonInfoListByDepartmentAsync(WinUI.Tiyi.PMS.GetPersonInfoListByDepartmentRequest request, object userState) {
            if ((this.onBeginGetPersonInfoListByDepartmentDelegate == null)) {
                this.onBeginGetPersonInfoListByDepartmentDelegate = new BeginOperationDelegate(this.OnBeginGetPersonInfoListByDepartment);
            }
            if ((this.onEndGetPersonInfoListByDepartmentDelegate == null)) {
                this.onEndGetPersonInfoListByDepartmentDelegate = new EndOperationDelegate(this.OnEndGetPersonInfoListByDepartment);
            }
            if ((this.onGetPersonInfoListByDepartmentCompletedDelegate == null)) {
                this.onGetPersonInfoListByDepartmentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPersonInfoListByDepartmentCompleted);
            }
            base.InvokeAsync(this.onBeginGetPersonInfoListByDepartmentDelegate, new object[] {
                        request}, this.onEndGetPersonInfoListByDepartmentDelegate, this.onGetPersonInfoListByDepartmentCompletedDelegate, userState);
        }
        
        public WinUI.Tiyi.PMS.ExistJobNumberResponse ExistJobNumber(WinUI.Tiyi.PMS.ExistJobNumberRequest request) {
            return base.Channel.ExistJobNumber(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginExistJobNumber(WinUI.Tiyi.PMS.ExistJobNumberRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExistJobNumber(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WinUI.Tiyi.PMS.ExistJobNumberResponse EndExistJobNumber(System.IAsyncResult result) {
            return base.Channel.EndExistJobNumber(result);
        }
        
        private System.IAsyncResult OnBeginExistJobNumber(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WinUI.Tiyi.PMS.ExistJobNumberRequest request = ((WinUI.Tiyi.PMS.ExistJobNumberRequest)(inValues[0]));
            return this.BeginExistJobNumber(request, callback, asyncState);
        }
        
        private object[] OnEndExistJobNumber(System.IAsyncResult result) {
            WinUI.Tiyi.PMS.ExistJobNumberResponse retVal = this.EndExistJobNumber(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExistJobNumberCompleted(object state) {
            if ((this.ExistJobNumberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExistJobNumberCompleted(this, new ExistJobNumberCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExistJobNumberAsync(WinUI.Tiyi.PMS.ExistJobNumberRequest request) {
            this.ExistJobNumberAsync(request, null);
        }
        
        public void ExistJobNumberAsync(WinUI.Tiyi.PMS.ExistJobNumberRequest request, object userState) {
            if ((this.onBeginExistJobNumberDelegate == null)) {
                this.onBeginExistJobNumberDelegate = new BeginOperationDelegate(this.OnBeginExistJobNumber);
            }
            if ((this.onEndExistJobNumberDelegate == null)) {
                this.onEndExistJobNumberDelegate = new EndOperationDelegate(this.OnEndExistJobNumber);
            }
            if ((this.onExistJobNumberCompletedDelegate == null)) {
                this.onExistJobNumberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExistJobNumberCompleted);
            }
            base.InvokeAsync(this.onBeginExistJobNumberDelegate, new object[] {
                        request}, this.onEndExistJobNumberDelegate, this.onExistJobNumberCompletedDelegate, userState);
        }
        
        public WinUI.Tiyi.PMS.GetDepartmentsResponse GetDepartments(WinUI.Tiyi.PMS.GetDepartmentsRequest request) {
            return base.Channel.GetDepartments(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDepartments(WinUI.Tiyi.PMS.GetDepartmentsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDepartments(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WinUI.Tiyi.PMS.GetDepartmentsResponse EndGetDepartments(System.IAsyncResult result) {
            return base.Channel.EndGetDepartments(result);
        }
        
        private System.IAsyncResult OnBeginGetDepartments(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WinUI.Tiyi.PMS.GetDepartmentsRequest request = ((WinUI.Tiyi.PMS.GetDepartmentsRequest)(inValues[0]));
            return this.BeginGetDepartments(request, callback, asyncState);
        }
        
        private object[] OnEndGetDepartments(System.IAsyncResult result) {
            WinUI.Tiyi.PMS.GetDepartmentsResponse retVal = this.EndGetDepartments(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDepartmentsCompleted(object state) {
            if ((this.GetDepartmentsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDepartmentsCompleted(this, new GetDepartmentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDepartmentsAsync(WinUI.Tiyi.PMS.GetDepartmentsRequest request) {
            this.GetDepartmentsAsync(request, null);
        }
        
        public void GetDepartmentsAsync(WinUI.Tiyi.PMS.GetDepartmentsRequest request, object userState) {
            if ((this.onBeginGetDepartmentsDelegate == null)) {
                this.onBeginGetDepartmentsDelegate = new BeginOperationDelegate(this.OnBeginGetDepartments);
            }
            if ((this.onEndGetDepartmentsDelegate == null)) {
                this.onEndGetDepartmentsDelegate = new EndOperationDelegate(this.OnEndGetDepartments);
            }
            if ((this.onGetDepartmentsCompletedDelegate == null)) {
                this.onGetDepartmentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDepartmentsCompleted);
            }
            base.InvokeAsync(this.onBeginGetDepartmentsDelegate, new object[] {
                        request}, this.onEndGetDepartmentsDelegate, this.onGetDepartmentsCompletedDelegate, userState);
        }
    }
}
