using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using org.in2bits.MyXls;

public partial class Admin_ShareOwnershipWithdrawal : System.Web.UI.Page
{
    ShareOS.BLL.ShareOwnershipManage bll_manage = new ShareOS.BLL.ShareOwnershipManage();
    ShareOS.BLL.SharesBonusManage bll_Bonus = new ShareOS.BLL.SharesBonusManage();
    ShareOS.BLL.ShareholderManage bll_sh = new ShareOS.BLL.ShareholderManage();

    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            Load_IssueNumber();
        }
    }

    private void Load_IssueNumber()
    {
        int currentIssueNumber = 0;
        currentIssueNumber = bll_Bonus.GetLastIssueNumber();
        ddlIssueNumber.Items.Clear();
        for (int i = currentIssueNumber; i >= 0; i--)
        {
            ddlIssueNumber.Items.Add(new ListItem(i.ToString()));
        }
    }

    protected void btnQuery_Click(object sender, EventArgs e)
    {
        odsChange.FilterExpression = "SharesChanges<0 and CauseOfChange='退股'";
        gvOwnershipChange.DataBind();
    }

    protected void btnExport_Click(object sender, EventArgs e)
    {
        int issueNumber = Convert.ToInt32(ddlIssueNumber.SelectedItem.Value);
        ExportReport(issueNumber);
    }

    /// <summary>
    /// 将社区物业房，导出Excel文档。
    /// </summary>
    /// <param name="issueNumber">股权交易期数。</param>
    private void ExportReport(int issueNumber)
    {
        //定义 Excel 文档实例。
        XlsDocument xlsDoc = new XlsDocument();
        //xlsDoc.FileName = System.IO.Path.GetFileName(fileName);


        //定义 Excel 文档属性.
        xlsDoc.SummaryInformation.Author = "Cobe lee";
        xlsDoc.SummaryInformation.Title = "股权清退汇总表";
        xlsDoc.SummaryInformation.Comments = "This workbook generated by ZPIT! http://www.zpit.com";
        xlsDoc.SummaryInformation.Subject = "股权清退汇总表";
        xlsDoc.DocumentSummaryInformation.Company = "镇海石化工业贸易有限责任公司";

        //定义输出的 Excel 文档的 文件名。
        System.Text.StringBuilder sbFileName = new System.Text.StringBuilder();
        sbFileName.Append("股权清退汇总表(");
        sbFileName.Append(System.DateTime.Now.Year.ToString());
        sbFileName.Append(System.DateTime.Now.Month.ToString().PadLeft(2, '0'));
        sbFileName.Append(System.DateTime.Now.Day.ToString().PadLeft(2, '0'));
        sbFileName.Append(")");

        sbFileName.Append(".xls");
        xlsDoc.FileName = HttpUtility.UrlEncode(sbFileName.ToString());

        //定义 Excel 文档中的 Sheet 表。
        Worksheet sheet = xlsDoc.Workbook.Worksheets.Add("Sheet1");
        xlsDoc.Workbook.Worksheets.Add("Sheet2");
        xlsDoc.Workbook.Worksheets.Add("Sheet3");
        Cells cells = sheet.Cells;

        //定义列标题样式
        XF colTitleXF = xlsDoc.NewXF();
        colTitleXF.UseBackground = true;
        colTitleXF.Pattern = 1;
        colTitleXF.PatternBackgroundColor = Colors.White;
        colTitleXF.PatternColor = Colors.Black;              //单元格背景色
        colTitleXF.Font.ColorIndex = 1;
        colTitleXF.Font.Height = 12 * 20;          //定义字体大小

        //定义 第一行信息
        cells.Add(1, 1, "镇海石化工业贸易有限责任公司");

        //定义 第二行信息
        cells.Merge(2, 2, 1, 8);
        Cell sheetTitle = cells.Add(2, 1, "股权清退汇总表");
        sheetTitle.Font.FontName = "微软雅黑";
        sheetTitle.Font.Height = 18 * 20;   //以字符的1/20为单位。
        sheetTitle.HorizontalAlignment = HorizontalAlignments.Centered;
        sheetTitle.VerticalAlignment = VerticalAlignments.Centered;

        //定义 第三行信息

        Cell cell1 = cells.Add(3, 1, "股权交易期数：" + issueNumber.ToString());
        cells.Add(3, 6, "制表时间");
        cells.Add(3, 7, System.DateTime.Today.ToShortDateString());
        //for (ushort i = 1; i < 7; i++)
        //{
        //    FormatCell(sheet.Rows[3].CellAtCol(i));
        //}


        //定义 Sheet 表中列名。
        int ColumnNameRow = 4;

        FormatCell(cells.Add(ColumnNameRow, 1, "序号", colTitleXF));
        FormatCell(cells.Add(ColumnNameRow, 2, "股东号", colTitleXF));
        FormatCell(cells.Add(ColumnNameRow, 3, "工号", colTitleXF));
        FormatCell(cells.Add(ColumnNameRow, 4, "姓名", colTitleXF));
        FormatCell(cells.Add(ColumnNameRow, 5, "性别", colTitleXF));
        FormatCell(cells.Add(ColumnNameRow, 6, "人员类别", colTitleXF));
        FormatCell(cells.Add(ColumnNameRow, 7, "代理人", colTitleXF));
        FormatCell(cells.Add(ColumnNameRow, 8, "清退股权数", colTitleXF));

        //定义列宽 ，数值为一个字符。
        SetColumnWidth(xlsDoc, sheet, 1, 8);
        SetColumnWidth(xlsDoc, sheet, 2, 8);
        SetColumnWidth(xlsDoc, sheet, 3, 10);
        SetColumnWidth(xlsDoc, sheet, 4, 10);
        SetColumnWidth(xlsDoc, sheet, 5, 6);
        SetColumnWidth(xlsDoc, sheet, 6, 20);
        SetColumnWidth(xlsDoc, sheet, 7, 10);
        SetColumnWidth(xlsDoc, sheet, 8, 16);

        int dataRow = ColumnNameRow + 1;
        int order = 1;

        //生成数据行。
        DataTable report = bll_manage.GetSharesWithdrawal(issueNumber);

        int rowCount = report.Rows.Count;

        for (int rowIndex = 0; rowIndex < rowCount; rowIndex++)
        {

            FormatCell(cells.Add(dataRow, 1, order));
            FormatCell(cells.Add(dataRow, 2, Convert.ToInt32(report.Rows[rowIndex]["ShareholderNumber"])));
            FormatCell(cells.Add(dataRow, 3, report.Rows[rowIndex]["JobNumber"].ToString()));
            FormatCell(cells.Add(dataRow, 4, report.Rows[rowIndex]["ShareholderName"].ToString()));
            FormatCell(cells.Add(dataRow, 5, Convert.ToBoolean(report.Rows[rowIndex]["Sex"]) ? "男" : "女"));
            FormatCell(cells.Add(dataRow, 6, report.Rows[rowIndex]["PersonType"].ToString()));
            FormatCell(cells.Add(dataRow, 7, report.Rows[rowIndex]["EntrustedAgentName"].ToString()));
            decimal changes = Convert.ToDecimal(report.Rows[rowIndex]["SharesChanges"]);
            FormatCell(cells.Add(dataRow, 8, changes));

            dataRow++; order++;
        }

        //string path = System.IO.Path.GetDirectoryName(fileName);

        this.Page.Response.ContentType = "application/x-excel";

        xlsDoc.Send();
        this.Page.Response.Flush();
        this.Page.Response.End();

    }

    private void FormatCell(Cell cell)
    {
        cell.UseBorder = true;

        cell.TopLineStyle = 1;
        cell.BottomLineStyle = 1;
        cell.RightLineStyle = 1;
        cell.LeftLineStyle = 1;
    }

    /// <summary>
    /// 设置列宽。
    /// </summary>
    /// <param name="xlsDoc">xls文件</param>
    /// <param name="sheet">表名称</param>
    /// <param name="colIndex">列索引，从1开始。</param>
    /// <param name="colWidth">列宽度，单位为一个字符宽。</param>
    private void SetColumnWidth(XlsDocument xlsDoc, Worksheet sheet, int colIndex, int colWidth)
    {
        if (colIndex > 0)
        {
            ColumnInfo col = new ColumnInfo(xlsDoc, sheet);
            col.ColumnIndexStart = (ushort)(colIndex - 1);
            col.ColumnIndexEnd = (ushort)(colIndex - 1);
            col.Width = (ushort)(colWidth * 256);
            sheet.AddColumnInfo(col);
        }

    }


    protected void btnConvert_Click(object sender, EventArgs e)
    {
        int issueNumber = Convert.ToInt32(ddlIssueNumber.SelectedItem.Value);
        DataTable report = bll_manage.GetSharesWithdrawal(issueNumber);

        int rowCount = report.Rows.Count;

        for (int rowIndex = 0; rowIndex < rowCount; rowIndex++)
        {
            int shnum = Convert.ToInt32(report.Rows[rowIndex]["ShareholderNumber"]);
            var sh = bll_sh.SelectShareholder(shnum);
            sh.Status = "待退股东";
        }
        bll_sh.Submit();
        gvOwnershipChange.DataBind();
    }
}