#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiyi.ShareOS.SQLServerDAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShareOS")]
	public partial class ShareDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertAgentAssistant(AgentAssistant instance);
    partial void UpdateAgentAssistant(AgentAssistant instance);
    partial void DeleteAgentAssistant(AgentAssistant instance);
    partial void InsertBonusRecord(BonusRecord instance);
    partial void UpdateBonusRecord(BonusRecord instance);
    partial void DeleteBonusRecord(BonusRecord instance);
    partial void InsertEntrustedAgent(EntrustedAgent instance);
    partial void UpdateEntrustedAgent(EntrustedAgent instance);
    partial void DeleteEntrustedAgent(EntrustedAgent instance);
    partial void InsertFundAccount(FundAccount instance);
    partial void UpdateFundAccount(FundAccount instance);
    partial void DeleteFundAccount(FundAccount instance);
    partial void InsertPersonType(PersonType instance);
    partial void UpdatePersonType(PersonType instance);
    partial void DeletePersonType(PersonType instance);
    partial void InsertSettlement(Settlement instance);
    partial void UpdateSettlement(Settlement instance);
    partial void DeleteSettlement(Settlement instance);
    partial void InsertShareholder(Shareholder instance);
    partial void UpdateShareholder(Shareholder instance);
    partial void DeleteShareholder(Shareholder instance);
    partial void InsertShareOwnership(ShareOwnership instance);
    partial void UpdateShareOwnership(ShareOwnership instance);
    partial void DeleteShareOwnership(ShareOwnership instance);
    partial void InsertShareOwnershipApply(ShareOwnershipApply instance);
    partial void UpdateShareOwnershipApply(ShareOwnershipApply instance);
    partial void DeleteShareOwnershipApply(ShareOwnershipApply instance);
    partial void InsertSharesIssueConfig(SharesIssueConfig instance);
    partial void UpdateSharesIssueConfig(SharesIssueConfig instance);
    partial void DeleteSharesIssueConfig(SharesIssueConfig instance);
    partial void InsertSysLogs(SysLogs instance);
    partial void UpdateSysLogs(SysLogs instance);
    partial void DeleteSysLogs(SysLogs instance);
    #endregion
		
		public ShareDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShareDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShareDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShareDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Account
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<AgentAssistant> AgentAssistant
		{
			get
			{
				return this.GetTable<AgentAssistant>();
			}
		}
		
		public System.Data.Linq.Table<BonusRecord> BonusRecord
		{
			get
			{
				return this.GetTable<BonusRecord>();
			}
		}
		
		public System.Data.Linq.Table<EntrustedAgent> EntrustedAgent
		{
			get
			{
				return this.GetTable<EntrustedAgent>();
			}
		}
		
		public System.Data.Linq.Table<FundAccount> FundAccount
		{
			get
			{
				return this.GetTable<FundAccount>();
			}
		}
		
		public System.Data.Linq.Table<PersonType> PersonType
		{
			get
			{
				return this.GetTable<PersonType>();
			}
		}
		
		public System.Data.Linq.Table<Settlement> Settlement
		{
			get
			{
				return this.GetTable<Settlement>();
			}
		}
		
		public System.Data.Linq.Table<Shareholder> Shareholder
		{
			get
			{
				return this.GetTable<Shareholder>();
			}
		}
		
		public System.Data.Linq.Table<ShareOwnership> ShareOwnership
		{
			get
			{
				return this.GetTable<ShareOwnership>();
			}
		}
		
		public System.Data.Linq.Table<ShareOwnershipApply> ShareOwnershipApply
		{
			get
			{
				return this.GetTable<ShareOwnershipApply>();
			}
		}
		
		public System.Data.Linq.Table<SharesIssueConfig> SharesIssueConfig
		{
			get
			{
				return this.GetTable<SharesIssueConfig>();
			}
		}
		
		public System.Data.Linq.Table<SysLogs> SysLogs
		{
			get
			{
				return this.GetTable<SysLogs>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserName;
		
		private string _Password;
		
		private string _UserType;
		
		private string _TrueName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    partial void OnTrueNameChanging(string value);
    partial void OnTrueNameChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NChar(32)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(32)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="NChar(32)")]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrueName", DbType="NChar(32)")]
		public string TrueName
		{
			get
			{
				return this._TrueName;
			}
			set
			{
				if ((this._TrueName != value))
				{
					this.OnTrueNameChanging(value);
					this.SendPropertyChanging();
					this._TrueName = value;
					this.SendPropertyChanged("TrueName");
					this.OnTrueNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AgentAssistant")]
	public partial class AgentAssistant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AgentShareholderNumber;
		
		private string _AssistantJobNumber;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAgentShareholderNumberChanging(int value);
    partial void OnAgentShareholderNumberChanged();
    partial void OnAssistantJobNumberChanging(string value);
    partial void OnAssistantJobNumberChanged();
    #endregion
		
		public AgentAssistant()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentShareholderNumber", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AgentShareholderNumber
		{
			get
			{
				return this._AgentShareholderNumber;
			}
			set
			{
				if ((this._AgentShareholderNumber != value))
				{
					this.OnAgentShareholderNumberChanging(value);
					this.SendPropertyChanging();
					this._AgentShareholderNumber = value;
					this.SendPropertyChanged("AgentShareholderNumber");
					this.OnAgentShareholderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssistantJobNumber", DbType="NChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AssistantJobNumber
		{
			get
			{
				return this._AssistantJobNumber;
			}
			set
			{
				if ((this._AssistantJobNumber != value))
				{
					this.OnAssistantJobNumberChanging(value);
					this.SendPropertyChanging();
					this._AssistantJobNumber = value;
					this.SendPropertyChanged("AssistantJobNumber");
					this.OnAssistantJobNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BonusRecord")]
	public partial class BonusRecord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IssueNumber;
		
		private int _ShareholderNumber;
		
		private System.Nullable<decimal> _CashBonus;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIssueNumberChanging(int value);
    partial void OnIssueNumberChanged();
    partial void OnShareholderNumberChanging(int value);
    partial void OnShareholderNumberChanged();
    partial void OnCashBonusChanging(System.Nullable<decimal> value);
    partial void OnCashBonusChanged();
    #endregion
		
		public BonusRecord()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueNumber", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IssueNumber
		{
			get
			{
				return this._IssueNumber;
			}
			set
			{
				if ((this._IssueNumber != value))
				{
					this.OnIssueNumberChanging(value);
					this.SendPropertyChanging();
					this._IssueNumber = value;
					this.SendPropertyChanged("IssueNumber");
					this.OnIssueNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShareholderNumber", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ShareholderNumber
		{
			get
			{
				return this._ShareholderNumber;
			}
			set
			{
				if ((this._ShareholderNumber != value))
				{
					this.OnShareholderNumberChanging(value);
					this.SendPropertyChanging();
					this._ShareholderNumber = value;
					this.SendPropertyChanged("ShareholderNumber");
					this.OnShareholderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashBonus", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CashBonus
		{
			get
			{
				return this._CashBonus;
			}
			set
			{
				if ((this._CashBonus != value))
				{
					this.OnCashBonusChanging(value);
					this.SendPropertyChanging();
					this._CashBonus = value;
					this.SendPropertyChanged("CashBonus");
					this.OnCashBonusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EntrustedAgent")]
	public partial class EntrustedAgent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ShareholderNumber;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnShareholderNumberChanging(int value);
    partial void OnShareholderNumberChanged();
    #endregion
		
		public EntrustedAgent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShareholderNumber", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ShareholderNumber
		{
			get
			{
				return this._ShareholderNumber;
			}
			set
			{
				if ((this._ShareholderNumber != value))
				{
					this.OnShareholderNumberChanging(value);
					this.SendPropertyChanging();
					this._ShareholderNumber = value;
					this.SendPropertyChanged("ShareholderNumber");
					this.OnShareholderNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FundAccount")]
	public partial class FundAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FundAccountId;
		
		private System.Nullable<int> _IssueNumber;
		
		private System.Nullable<int> _ShareholderNumber;
		
		private System.Nullable<decimal> _ChangeMoney;
		
		private string _ChangeReason;
		
		private System.Nullable<System.DateTime> _ChangeDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFundAccountIdChanging(int value);
    partial void OnFundAccountIdChanged();
    partial void OnIssueNumberChanging(System.Nullable<int> value);
    partial void OnIssueNumberChanged();
    partial void OnShareholderNumberChanging(System.Nullable<int> value);
    partial void OnShareholderNumberChanged();
    partial void OnChangeMoneyChanging(System.Nullable<decimal> value);
    partial void OnChangeMoneyChanged();
    partial void OnChangeReasonChanging(string value);
    partial void OnChangeReasonChanged();
    partial void OnChangeDateChanging(System.Nullable<System.DateTime> value);
    partial void OnChangeDateChanged();
    #endregion
		
		public FundAccount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FundAccountId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FundAccountId
		{
			get
			{
				return this._FundAccountId;
			}
			set
			{
				if ((this._FundAccountId != value))
				{
					this.OnFundAccountIdChanging(value);
					this.SendPropertyChanging();
					this._FundAccountId = value;
					this.SendPropertyChanged("FundAccountId");
					this.OnFundAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueNumber", DbType="Int")]
		public System.Nullable<int> IssueNumber
		{
			get
			{
				return this._IssueNumber;
			}
			set
			{
				if ((this._IssueNumber != value))
				{
					this.OnIssueNumberChanging(value);
					this.SendPropertyChanging();
					this._IssueNumber = value;
					this.SendPropertyChanged("IssueNumber");
					this.OnIssueNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShareholderNumber", DbType="Int")]
		public System.Nullable<int> ShareholderNumber
		{
			get
			{
				return this._ShareholderNumber;
			}
			set
			{
				if ((this._ShareholderNumber != value))
				{
					this.OnShareholderNumberChanging(value);
					this.SendPropertyChanging();
					this._ShareholderNumber = value;
					this.SendPropertyChanged("ShareholderNumber");
					this.OnShareholderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeMoney", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ChangeMoney
		{
			get
			{
				return this._ChangeMoney;
			}
			set
			{
				if ((this._ChangeMoney != value))
				{
					this.OnChangeMoneyChanging(value);
					this.SendPropertyChanging();
					this._ChangeMoney = value;
					this.SendPropertyChanged("ChangeMoney");
					this.OnChangeMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeReason", DbType="NVarChar(32)")]
		public string ChangeReason
		{
			get
			{
				return this._ChangeReason;
			}
			set
			{
				if ((this._ChangeReason != value))
				{
					this.OnChangeReasonChanging(value);
					this.SendPropertyChanging();
					this._ChangeReason = value;
					this.SendPropertyChanged("ChangeReason");
					this.OnChangeReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangeDate
		{
			get
			{
				return this._ChangeDate;
			}
			set
			{
				if ((this._ChangeDate != value))
				{
					this.OnChangeDateChanging(value);
					this.SendPropertyChanging();
					this._ChangeDate = value;
					this.SendPropertyChanged("ChangeDate");
					this.OnChangeDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonType")]
	public partial class PersonType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PersonTypeName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonTypeNameChanging(string value);
    partial void OnPersonTypeNameChanged();
    #endregion
		
		public PersonType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonTypeName", DbType="NVarChar(32) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PersonTypeName
		{
			get
			{
				return this._PersonTypeName;
			}
			set
			{
				if ((this._PersonTypeName != value))
				{
					this.OnPersonTypeNameChanging(value);
					this.SendPropertyChanging();
					this._PersonTypeName = value;
					this.SendPropertyChanged("PersonTypeName");
					this.OnPersonTypeNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Settlement")]
	public partial class Settlement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _SId;
		
		private int _IssueNumber;
		
		private int _ShareholderNumber;
		
		private decimal _OpeningShares;
		
		private decimal _DonateShares;
		
		private decimal _SellingShares;
		
		private decimal _SharePrice;
		
		private decimal _Amount;
		
		private decimal _IncomeTax;
		
		private decimal _Yingfa;
		
		private string _SettlementType;
		
		private decimal _ClosingShares;
		
		private System.DateTime _DateTime;
		
		private string _Operator;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIdChanging(System.Guid value);
    partial void OnSIdChanged();
    partial void OnIssueNumberChanging(int value);
    partial void OnIssueNumberChanged();
    partial void OnShareholderNumberChanging(int value);
    partial void OnShareholderNumberChanged();
    partial void OnOpeningSharesChanging(decimal value);
    partial void OnOpeningSharesChanged();
    partial void OnDonateSharesChanging(decimal value);
    partial void OnDonateSharesChanged();
    partial void OnSellingSharesChanging(decimal value);
    partial void OnSellingSharesChanged();
    partial void OnSharePriceChanging(decimal value);
    partial void OnSharePriceChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    partial void OnIncomeTaxChanging(decimal value);
    partial void OnIncomeTaxChanged();
    partial void OnYingfaChanging(decimal value);
    partial void OnYingfaChanged();
    partial void OnSettlementTypeChanging(string value);
    partial void OnSettlementTypeChanged();
    partial void OnClosingSharesChanging(decimal value);
    partial void OnClosingSharesChanged();
    partial void OnDateTimeChanging(System.DateTime value);
    partial void OnDateTimeChanged();
    partial void OnOperatorChanging(string value);
    partial void OnOperatorChanged();
    #endregion
		
		public Settlement()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid SId
		{
			get
			{
				return this._SId;
			}
			set
			{
				if ((this._SId != value))
				{
					this.OnSIdChanging(value);
					this.SendPropertyChanging();
					this._SId = value;
					this.SendPropertyChanged("SId");
					this.OnSIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueNumber", DbType="Int NOT NULL")]
		public int IssueNumber
		{
			get
			{
				return this._IssueNumber;
			}
			set
			{
				if ((this._IssueNumber != value))
				{
					this.OnIssueNumberChanging(value);
					this.SendPropertyChanging();
					this._IssueNumber = value;
					this.SendPropertyChanged("IssueNumber");
					this.OnIssueNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShareholderNumber", DbType="Int NOT NULL")]
		public int ShareholderNumber
		{
			get
			{
				return this._ShareholderNumber;
			}
			set
			{
				if ((this._ShareholderNumber != value))
				{
					this.OnShareholderNumberChanging(value);
					this.SendPropertyChanging();
					this._ShareholderNumber = value;
					this.SendPropertyChanged("ShareholderNumber");
					this.OnShareholderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpeningShares", DbType="Decimal(18,4) NOT NULL")]
		public decimal OpeningShares
		{
			get
			{
				return this._OpeningShares;
			}
			set
			{
				if ((this._OpeningShares != value))
				{
					this.OnOpeningSharesChanging(value);
					this.SendPropertyChanging();
					this._OpeningShares = value;
					this.SendPropertyChanged("OpeningShares");
					this.OnOpeningSharesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonateShares", DbType="Decimal(18,4) NOT NULL")]
		public decimal DonateShares
		{
			get
			{
				return this._DonateShares;
			}
			set
			{
				if ((this._DonateShares != value))
				{
					this.OnDonateSharesChanging(value);
					this.SendPropertyChanging();
					this._DonateShares = value;
					this.SendPropertyChanged("DonateShares");
					this.OnDonateSharesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellingShares", DbType="Decimal(18,4) NOT NULL")]
		public decimal SellingShares
		{
			get
			{
				return this._SellingShares;
			}
			set
			{
				if ((this._SellingShares != value))
				{
					this.OnSellingSharesChanging(value);
					this.SendPropertyChanging();
					this._SellingShares = value;
					this.SendPropertyChanged("SellingShares");
					this.OnSellingSharesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SharePrice", DbType="Decimal(18,4) NOT NULL")]
		public decimal SharePrice
		{
			get
			{
				return this._SharePrice;
			}
			set
			{
				if ((this._SharePrice != value))
				{
					this.OnSharePriceChanging(value);
					this.SendPropertyChanging();
					this._SharePrice = value;
					this.SendPropertyChanged("SharePrice");
					this.OnSharePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,4) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncomeTax", DbType="Decimal(18,4) NOT NULL")]
		public decimal IncomeTax
		{
			get
			{
				return this._IncomeTax;
			}
			set
			{
				if ((this._IncomeTax != value))
				{
					this.OnIncomeTaxChanging(value);
					this.SendPropertyChanging();
					this._IncomeTax = value;
					this.SendPropertyChanged("IncomeTax");
					this.OnIncomeTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yingfa", DbType="Decimal(18,4) NOT NULL")]
		public decimal Yingfa
		{
			get
			{
				return this._Yingfa;
			}
			set
			{
				if ((this._Yingfa != value))
				{
					this.OnYingfaChanging(value);
					this.SendPropertyChanging();
					this._Yingfa = value;
					this.SendPropertyChanged("Yingfa");
					this.OnYingfaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettlementType", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string SettlementType
		{
			get
			{
				return this._SettlementType;
			}
			set
			{
				if ((this._SettlementType != value))
				{
					this.OnSettlementTypeChanging(value);
					this.SendPropertyChanging();
					this._SettlementType = value;
					this.SendPropertyChanged("SettlementType");
					this.OnSettlementTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosingShares", DbType="Decimal(18,4) NOT NULL")]
		public decimal ClosingShares
		{
			get
			{
				return this._ClosingShares;
			}
			set
			{
				if ((this._ClosingShares != value))
				{
					this.OnClosingSharesChanging(value);
					this.SendPropertyChanging();
					this._ClosingShares = value;
					this.SendPropertyChanged("ClosingShares");
					this.OnClosingSharesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime NOT NULL")]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this.OnOperatorChanging(value);
					this.SendPropertyChanging();
					this._Operator = value;
					this.SendPropertyChanged("Operator");
					this.OnOperatorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shareholder")]
	public partial class Shareholder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ShareholderId;
		
		private int _ShareholderNumber;
		
		private System.Data.Linq.Binary _BarCode;
		
		private string _JobNumber;
		
		private string _ShareholderName;
		
		private System.Nullable<bool> _Sex;
		
		private string _IdentityCard;
		
		private string _PersonType;
		
		private string _Status;
		
		private System.Nullable<int> _EntrustedAgent;
		
		private string _DepName;
		
		private string _AccountHolder;
		
		private string _BankName;
		
		private string _AccountNumber;
		
		private bool _FrozenTag;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnShareholderIdChanging(int value);
    partial void OnShareholderIdChanged();
    partial void OnShareholderNumberChanging(int value);
    partial void OnShareholderNumberChanged();
    partial void OnBarCodeChanging(System.Data.Linq.Binary value);
    partial void OnBarCodeChanged();
    partial void OnJobNumberChanging(string value);
    partial void OnJobNumberChanged();
    partial void OnShareholderNameChanging(string value);
    partial void OnShareholderNameChanged();
    partial void OnSexChanging(System.Nullable<bool> value);
    partial void OnSexChanged();
    partial void OnIdentityCardChanging(string value);
    partial void OnIdentityCardChanged();
    partial void OnPersonTypeChanging(string value);
    partial void OnPersonTypeChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnEntrustedAgentChanging(System.Nullable<int> value);
    partial void OnEntrustedAgentChanged();
    partial void OnDepNameChanging(string value);
    partial void OnDepNameChanged();
    partial void OnAccountHolderChanging(string value);
    partial void OnAccountHolderChanged();
    partial void OnBankNameChanging(string value);
    partial void OnBankNameChanged();
    partial void OnAccountNumberChanging(string value);
    partial void OnAccountNumberChanged();
    partial void OnFrozenTagChanging(bool value);
    partial void OnFrozenTagChanged();
    #endregion
		
		public Shareholder()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShareholderId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ShareholderId
		{
			get
			{
				return this._ShareholderId;
			}
			set
			{
				if ((this._ShareholderId != value))
				{
					this.OnShareholderIdChanging(value);
					this.SendPropertyChanging();
					this._ShareholderId = value;
					this.SendPropertyChanged("ShareholderId");
					this.OnShareholderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShareholderNumber", DbType="Int NOT NULL")]
		public int ShareholderNumber
		{
			get
			{
				return this._ShareholderNumber;
			}
			set
			{
				if ((this._ShareholderNumber != value))
				{
					this.OnShareholderNumberChanging(value);
					this.SendPropertyChanging();
					this._ShareholderNumber = value;
					this.SendPropertyChanged("ShareholderNumber");
					this.OnShareholderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary BarCode
		{
			get
			{
				return this._BarCode;
			}
			set
			{
				if ((this._BarCode != value))
				{
					this.OnBarCodeChanging(value);
					this.SendPropertyChanging();
					this._BarCode = value;
					this.SendPropertyChanged("BarCode");
					this.OnBarCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobNumber", DbType="NChar(6)")]
		public string JobNumber
		{
			get
			{
				return this._JobNumber;
			}
			set
			{
				if ((this._JobNumber != value))
				{
					this.OnJobNumberChanging(value);
					this.SendPropertyChanging();
					this._JobNumber = value;
					this.SendPropertyChanged("JobNumber");
					this.OnJobNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShareholderName", DbType="NVarChar(16)")]
		public string ShareholderName
		{
			get
			{
				return this._ShareholderName;
			}
			set
			{
				if ((this._ShareholderName != value))
				{
					this.OnShareholderNameChanging(value);
					this.SendPropertyChanging();
					this._ShareholderName = value;
					this.SendPropertyChanged("ShareholderName");
					this.OnShareholderNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Bit")]
		public System.Nullable<bool> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentityCard", DbType="NChar(18)")]
		public string IdentityCard
		{
			get
			{
				return this._IdentityCard;
			}
			set
			{
				if ((this._IdentityCard != value))
				{
					this.OnIdentityCardChanging(value);
					this.SendPropertyChanging();
					this._IdentityCard = value;
					this.SendPropertyChanged("IdentityCard");
					this.OnIdentityCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonType", DbType="NVarChar(32)")]
		public string PersonType
		{
			get
			{
				return this._PersonType;
			}
			set
			{
				if ((this._PersonType != value))
				{
					this.OnPersonTypeChanging(value);
					this.SendPropertyChanging();
					this._PersonType = value;
					this.SendPropertyChanged("PersonType");
					this.OnPersonTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(16)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntrustedAgent", DbType="Int")]
		public System.Nullable<int> EntrustedAgent
		{
			get
			{
				return this._EntrustedAgent;
			}
			set
			{
				if ((this._EntrustedAgent != value))
				{
					this.OnEntrustedAgentChanging(value);
					this.SendPropertyChanging();
					this._EntrustedAgent = value;
					this.SendPropertyChanged("EntrustedAgent");
					this.OnEntrustedAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepName", DbType="NVarChar(32)")]
		public string DepName
		{
			get
			{
				return this._DepName;
			}
			set
			{
				if ((this._DepName != value))
				{
					this.OnDepNameChanging(value);
					this.SendPropertyChanging();
					this._DepName = value;
					this.SendPropertyChanged("DepName");
					this.OnDepNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountHolder", DbType="NVarChar(32)")]
		public string AccountHolder
		{
			get
			{
				return this._AccountHolder;
			}
			set
			{
				if ((this._AccountHolder != value))
				{
					this.OnAccountHolderChanging(value);
					this.SendPropertyChanging();
					this._AccountHolder = value;
					this.SendPropertyChanged("AccountHolder");
					this.OnAccountHolderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="NVarChar(32)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this.OnBankNameChanging(value);
					this.SendPropertyChanging();
					this._BankName = value;
					this.SendPropertyChanged("BankName");
					this.OnBankNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="NVarChar(32)")]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this.OnAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._AccountNumber = value;
					this.SendPropertyChanged("AccountNumber");
					this.OnAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrozenTag", DbType="Bit NOT NULL")]
		public bool FrozenTag
		{
			get
			{
				return this._FrozenTag;
			}
			set
			{
				if ((this._FrozenTag != value))
				{
					this.OnFrozenTagChanging(value);
					this.SendPropertyChanging();
					this._FrozenTag = value;
					this.SendPropertyChanged("FrozenTag");
					this.OnFrozenTagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShareOwnership")]
	public partial class ShareOwnership : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RegId;
		
		private System.Nullable<int> _IssueNumber;
		
		private int _ShareholderNumber;
		
		private System.Nullable<decimal> _SharesChanges;
		
		private System.Nullable<decimal> _ShareTotals;
		
		private System.Nullable<decimal> _OriginalSharePrice;
		
		private string _CauseOfChange;
		
		private System.Nullable<bool> _IsPrincipal;
		
		private System.Nullable<System.DateTime> _RegDate;
		
		private string _Operator;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegIdChanging(int value);
    partial void OnRegIdChanged();
    partial void OnIssueNumberChanging(System.Nullable<int> value);
    partial void OnIssueNumberChanged();
    partial void OnShareholderNumberChanging(int value);
    partial void OnShareholderNumberChanged();
    partial void OnSharesChangesChanging(System.Nullable<decimal> value);
    partial void OnSharesChangesChanged();
    partial void OnShareTotalsChanging(System.Nullable<decimal> value);
    partial void OnShareTotalsChanged();
    partial void OnOriginalSharePriceChanging(System.Nullable<decimal> value);
    partial void OnOriginalSharePriceChanged();
    partial void OnCauseOfChangeChanging(string value);
    partial void OnCauseOfChangeChanged();
    partial void OnIsPrincipalChanging(System.Nullable<bool> value);
    partial void OnIsPrincipalChanged();
    partial void OnRegDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegDateChanged();
    partial void OnOperatorChanging(string value);
    partial void OnOperatorChanged();
    #endregion
		
		public ShareOwnership()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RegId
		{
			get
			{
				return this._RegId;
			}
			set
			{
				if ((this._RegId != value))
				{
					this.OnRegIdChanging(value);
					this.SendPropertyChanging();
					this._RegId = value;
					this.SendPropertyChanged("RegId");
					this.OnRegIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueNumber", DbType="Int")]
		public System.Nullable<int> IssueNumber
		{
			get
			{
				return this._IssueNumber;
			}
			set
			{
				if ((this._IssueNumber != value))
				{
					this.OnIssueNumberChanging(value);
					this.SendPropertyChanging();
					this._IssueNumber = value;
					this.SendPropertyChanged("IssueNumber");
					this.OnIssueNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShareholderNumber", DbType="Int NOT NULL")]
		public int ShareholderNumber
		{
			get
			{
				return this._ShareholderNumber;
			}
			set
			{
				if ((this._ShareholderNumber != value))
				{
					this.OnShareholderNumberChanging(value);
					this.SendPropertyChanging();
					this._ShareholderNumber = value;
					this.SendPropertyChanged("ShareholderNumber");
					this.OnShareholderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SharesChanges", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> SharesChanges
		{
			get
			{
				return this._SharesChanges;
			}
			set
			{
				if ((this._SharesChanges != value))
				{
					this.OnSharesChangesChanging(value);
					this.SendPropertyChanging();
					this._SharesChanges = value;
					this.SendPropertyChanged("SharesChanges");
					this.OnSharesChangesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShareTotals", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> ShareTotals
		{
			get
			{
				return this._ShareTotals;
			}
			set
			{
				if ((this._ShareTotals != value))
				{
					this.OnShareTotalsChanging(value);
					this.SendPropertyChanging();
					this._ShareTotals = value;
					this.SendPropertyChanged("ShareTotals");
					this.OnShareTotalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalSharePrice", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> OriginalSharePrice
		{
			get
			{
				return this._OriginalSharePrice;
			}
			set
			{
				if ((this._OriginalSharePrice != value))
				{
					this.OnOriginalSharePriceChanging(value);
					this.SendPropertyChanging();
					this._OriginalSharePrice = value;
					this.SendPropertyChanged("OriginalSharePrice");
					this.OnOriginalSharePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CauseOfChange", DbType="NVarChar(16)")]
		public string CauseOfChange
		{
			get
			{
				return this._CauseOfChange;
			}
			set
			{
				if ((this._CauseOfChange != value))
				{
					this.OnCauseOfChangeChanging(value);
					this.SendPropertyChanging();
					this._CauseOfChange = value;
					this.SendPropertyChanged("CauseOfChange");
					this.OnCauseOfChangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrincipal", DbType="Bit")]
		public System.Nullable<bool> IsPrincipal
		{
			get
			{
				return this._IsPrincipal;
			}
			set
			{
				if ((this._IsPrincipal != value))
				{
					this.OnIsPrincipalChanging(value);
					this.SendPropertyChanging();
					this._IsPrincipal = value;
					this.SendPropertyChanged("IsPrincipal");
					this.OnIsPrincipalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RegDate
		{
			get
			{
				return this._RegDate;
			}
			set
			{
				if ((this._RegDate != value))
				{
					this.OnRegDateChanging(value);
					this.SendPropertyChanging();
					this._RegDate = value;
					this.SendPropertyChanged("RegDate");
					this.OnRegDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="NVarChar(16)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this.OnOperatorChanging(value);
					this.SendPropertyChanging();
					this._Operator = value;
					this.SendPropertyChanged("Operator");
					this.OnOperatorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShareOwnershipApply")]
	public partial class ShareOwnershipApply : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IssueNumber;
		
		private System.Nullable<int> _ShareholderNumber;
		
		private System.Nullable<int> _SharesAmount;
		
		private System.Nullable<System.DateTime> _DateOfApply;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIssueNumberChanging(System.Nullable<int> value);
    partial void OnIssueNumberChanged();
    partial void OnShareholderNumberChanging(System.Nullable<int> value);
    partial void OnShareholderNumberChanged();
    partial void OnSharesAmountChanging(System.Nullable<int> value);
    partial void OnSharesAmountChanged();
    partial void OnDateOfApplyChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfApplyChanged();
    #endregion
		
		public ShareOwnershipApply()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueNumber", DbType="Int")]
		public System.Nullable<int> IssueNumber
		{
			get
			{
				return this._IssueNumber;
			}
			set
			{
				if ((this._IssueNumber != value))
				{
					this.OnIssueNumberChanging(value);
					this.SendPropertyChanging();
					this._IssueNumber = value;
					this.SendPropertyChanged("IssueNumber");
					this.OnIssueNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShareholderNumber", DbType="Int")]
		public System.Nullable<int> ShareholderNumber
		{
			get
			{
				return this._ShareholderNumber;
			}
			set
			{
				if ((this._ShareholderNumber != value))
				{
					this.OnShareholderNumberChanging(value);
					this.SendPropertyChanging();
					this._ShareholderNumber = value;
					this.SendPropertyChanged("ShareholderNumber");
					this.OnShareholderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SharesAmount", DbType="Int")]
		public System.Nullable<int> SharesAmount
		{
			get
			{
				return this._SharesAmount;
			}
			set
			{
				if ((this._SharesAmount != value))
				{
					this.OnSharesAmountChanging(value);
					this.SendPropertyChanging();
					this._SharesAmount = value;
					this.SendPropertyChanged("SharesAmount");
					this.OnSharesAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfApply", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateOfApply
		{
			get
			{
				return this._DateOfApply;
			}
			set
			{
				if ((this._DateOfApply != value))
				{
					this.OnDateOfApplyChanging(value);
					this.SendPropertyChanging();
					this._DateOfApply = value;
					this.SendPropertyChanged("DateOfApply");
					this.OnDateOfApplyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SharesIssueConfig")]
	public partial class SharesIssueConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SICId;
		
		private System.Nullable<int> _IssueNumber;
		
		private System.Nullable<int> _IssueYear;
		
		private string _DisplayText;
		
		private System.Nullable<decimal> _Bonus;
		
		private System.Nullable<System.DateTime> _DPD;
		
		private System.Nullable<decimal> _SharePrice;
		
		private System.Nullable<bool> _IsDistributed;
		
		private bool _IsOpen;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSICIdChanging(int value);
    partial void OnSICIdChanged();
    partial void OnIssueNumberChanging(System.Nullable<int> value);
    partial void OnIssueNumberChanged();
    partial void OnIssueYearChanging(System.Nullable<int> value);
    partial void OnIssueYearChanged();
    partial void OnDisplayTextChanging(string value);
    partial void OnDisplayTextChanged();
    partial void OnBonusChanging(System.Nullable<decimal> value);
    partial void OnBonusChanged();
    partial void OnDPDChanging(System.Nullable<System.DateTime> value);
    partial void OnDPDChanged();
    partial void OnSharePriceChanging(System.Nullable<decimal> value);
    partial void OnSharePriceChanged();
    partial void OnIsDistributedChanging(System.Nullable<bool> value);
    partial void OnIsDistributedChanged();
    partial void OnIsOpenChanging(bool value);
    partial void OnIsOpenChanged();
    #endregion
		
		public SharesIssueConfig()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SICId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SICId
		{
			get
			{
				return this._SICId;
			}
			set
			{
				if ((this._SICId != value))
				{
					this.OnSICIdChanging(value);
					this.SendPropertyChanging();
					this._SICId = value;
					this.SendPropertyChanged("SICId");
					this.OnSICIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueNumber", DbType="Int")]
		public System.Nullable<int> IssueNumber
		{
			get
			{
				return this._IssueNumber;
			}
			set
			{
				if ((this._IssueNumber != value))
				{
					this.OnIssueNumberChanging(value);
					this.SendPropertyChanging();
					this._IssueNumber = value;
					this.SendPropertyChanged("IssueNumber");
					this.OnIssueNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueYear", DbType="Int")]
		public System.Nullable<int> IssueYear
		{
			get
			{
				return this._IssueYear;
			}
			set
			{
				if ((this._IssueYear != value))
				{
					this.OnIssueYearChanging(value);
					this.SendPropertyChanging();
					this._IssueYear = value;
					this.SendPropertyChanged("IssueYear");
					this.OnIssueYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayText", DbType="NVarChar(32)")]
		public string DisplayText
		{
			get
			{
				return this._DisplayText;
			}
			set
			{
				if ((this._DisplayText != value))
				{
					this.OnDisplayTextChanging(value);
					this.SendPropertyChanging();
					this._DisplayText = value;
					this.SendPropertyChanged("DisplayText");
					this.OnDisplayTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bonus", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Bonus
		{
			get
			{
				return this._Bonus;
			}
			set
			{
				if ((this._Bonus != value))
				{
					this.OnBonusChanging(value);
					this.SendPropertyChanging();
					this._Bonus = value;
					this.SendPropertyChanged("Bonus");
					this.OnBonusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPD", DbType="DateTime")]
		public System.Nullable<System.DateTime> DPD
		{
			get
			{
				return this._DPD;
			}
			set
			{
				if ((this._DPD != value))
				{
					this.OnDPDChanging(value);
					this.SendPropertyChanging();
					this._DPD = value;
					this.SendPropertyChanged("DPD");
					this.OnDPDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SharePrice", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> SharePrice
		{
			get
			{
				return this._SharePrice;
			}
			set
			{
				if ((this._SharePrice != value))
				{
					this.OnSharePriceChanging(value);
					this.SendPropertyChanging();
					this._SharePrice = value;
					this.SendPropertyChanged("SharePrice");
					this.OnSharePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDistributed", DbType="Bit")]
		public System.Nullable<bool> IsDistributed
		{
			get
			{
				return this._IsDistributed;
			}
			set
			{
				if ((this._IsDistributed != value))
				{
					this.OnIsDistributedChanging(value);
					this.SendPropertyChanging();
					this._IsDistributed = value;
					this.SendPropertyChanged("IsDistributed");
					this.OnIsDistributedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOpen", DbType="Bit NOT NULL")]
		public bool IsOpen
		{
			get
			{
				return this._IsOpen;
			}
			set
			{
				if ((this._IsOpen != value))
				{
					this.OnIsOpenChanging(value);
					this.SendPropertyChanging();
					this._IsOpen = value;
					this.SendPropertyChanged("IsOpen");
					this.OnIsOpenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SysLogs")]
	public partial class SysLogs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LogId;
		
		private string _LogType;
		
		private System.Nullable<System.DateTime> _LogDateTime;
		
		private string _Source;
		
		private string _Description;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogIdChanging(int value);
    partial void OnLogIdChanged();
    partial void OnLogTypeChanging(string value);
    partial void OnLogTypeChanged();
    partial void OnLogDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLogDateTimeChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public SysLogs()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LogId
		{
			get
			{
				return this._LogId;
			}
			set
			{
				if ((this._LogId != value))
				{
					this.OnLogIdChanging(value);
					this.SendPropertyChanging();
					this._LogId = value;
					this.SendPropertyChanged("LogId");
					this.OnLogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogType", DbType="NVarChar(16)")]
		public string LogType
		{
			get
			{
				return this._LogType;
			}
			set
			{
				if ((this._LogType != value))
				{
					this.OnLogTypeChanging(value);
					this.SendPropertyChanging();
					this._LogType = value;
					this.SendPropertyChanged("LogType");
					this.OnLogTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LogDateTime
		{
			get
			{
				return this._LogDateTime;
			}
			set
			{
				if ((this._LogDateTime != value))
				{
					this.OnLogDateTimeChanging(value);
					this.SendPropertyChanging();
					this._LogDateTime = value;
					this.SendPropertyChanged("LogDateTime");
					this.OnLogDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(16)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(128)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
